#
# Vagrantfile for a CentOS Linux Box with Reprozip and Bertini
#
#
Vagrant.configure(2) do |config|
  
  config.vm.box = "centos/7"
  config.vm.hostname = "bertinivm"

  # Disable automatic box update checking. 
  config.vm.box_check_update = false

  #
   config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
	vb.memory = "4096"
	vb.cpus = 2
        vb.name = "bertini-reprozip"
   end

  config.vm.provision "shell", inline: "yum -y install epel-release"
  config.vm.provision "shell", inline: "yum -y install patch"
  config.vm.provision "shell", inline: "yum -y install wget"
  config.vm.provision "shell", inline: "yum -y install gcc"
  config.vm.provision "shell", inline: "yum -y install sqlite"
  config.vm.provision "shell", inline: "yum -y install sqlite-devel"
  config.vm.provision "shell", inline: "yum -y install git"
  config.vm.provision "shell", inline: "yum -y install python"
  config.vm.provision "shell", inline: "yum -y install python-pip"
  config.vm.provision "shell", inline: "yum -y install python-devel"
  config.vm.provision "shell", inline: "wget https://bertini.nd.edu/BertiniLinux64_v1.5.tar.gz"
  config.vm.provision "shell", inline: "tar --owner vagrant -xzvf BertiniLinux64_v1.5.tar.gz"
  config.vm.provision "shell", inline: "pip install reprozip"

end
